<?php

namespace Database\Seeders;

use App\Models\JobListing;
use Illuminate\Database\Seeder;

class JobListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Senior Laravel Developer',
                'company_name' => 'TechCorp Solutions',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=TC&background=4F46E5&color=fff',
                'location' => 'San Francisco, CA',
                'salary_min' => 120000,
                'salary_max' => 160000,
                'job_type' => 'Full-time',
                'location_type' => 'Remote',
                'description' => 'We are looking for a Senior Laravel Developer to join our growing team. You will be responsible for building and maintaining scalable web applications, mentoring junior developers, and contributing to architectural decisions. Experience with microservices, queue systems, and CI/CD pipelines is highly valued.',
                'skills' => ['PHP', 'Laravel', 'MySQL', 'Redis', 'Docker'],
                'created_at' => now()->subDays(1),
            ],
            [
                'title' => 'Frontend React Engineer',
                'company_name' => 'PixelWave Studios',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=PW&background=EC4899&color=fff',
                'location' => 'New York, NY',
                'salary_min' => 110000,
                'salary_max' => 145000,
                'job_type' => 'Full-time',
                'location_type' => 'Hybrid',
                'description' => 'Join our creative team to build stunning user interfaces for our SaaS platform. You will work closely with designers and backend engineers to deliver pixel-perfect, performant web applications using React and TypeScript.',
                'skills' => ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'GraphQL'],
                'created_at' => now()->subDays(2),
            ],
            [
                'title' => 'DevOps Engineer',
                'company_name' => 'CloudNine Infrastructure',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=CN&background=10B981&color=fff',
                'location' => 'Austin, TX',
                'salary_min' => 130000,
                'salary_max' => 170000,
                'job_type' => 'Full-time',
                'location_type' => 'On-site',
                'description' => 'We need a DevOps Engineer to manage our cloud infrastructure, implement CI/CD pipelines, and ensure high availability of our services. You will work with Kubernetes, Terraform, and AWS to build resilient systems.',
                'skills' => ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'Linux'],
                'created_at' => now()->subDays(3),
            ],
            [
                'title' => 'Part-time Content Writer',
                'company_name' => 'BlogSphere Media',
                'company_logo_url' => null,
                'location' => 'Chicago, IL',
                'salary_min' => 25000,
                'salary_max' => 40000,
                'job_type' => 'Part-time',
                'location_type' => 'Remote',
                'description' => 'We are seeking a talented content writer to produce engaging blog posts, articles, and marketing copy. This is a part-time role perfect for writers who want flexibility while working on diverse topics in the tech industry.',
                'skills' => ['Content Writing', 'SEO', 'WordPress', 'Copywriting'],
                'created_at' => now()->subDays(4),
            ],
            [
                'title' => 'Mobile App Developer (Contract)',
                'company_name' => 'AppForge Inc.',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=AF&background=F59E0B&color=fff',
                'location' => 'Seattle, WA',
                'salary_min' => 80000,
                'salary_max' => 120000,
                'job_type' => 'Contract',
                'location_type' => 'Remote',
                'description' => 'We have a 6-month contract opportunity for a mobile developer to build a cross-platform application using React Native. The project involves integrating with existing REST APIs and implementing offline-first capabilities.',
                'skills' => ['React Native', 'JavaScript', 'iOS', 'Android', 'REST APIs'],
                'created_at' => now()->subDays(5),
            ],
            [
                'title' => 'UX/UI Design Intern',
                'company_name' => 'DesignHub Creative',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=DH&background=8B5CF6&color=fff',
                'location' => 'Los Angeles, CA',
                'salary_min' => 20000,
                'salary_max' => 30000,
                'job_type' => 'Internship',
                'location_type' => 'On-site',
                'description' => 'Great opportunity for design students to gain hands-on experience in UX/UI design. You will work alongside senior designers on real client projects, conduct user research, create wireframes, and build interactive prototypes.',
                'skills' => ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Wireframing'],
                'created_at' => now()->subDays(6),
            ],
            [
                'title' => 'Freelance WordPress Developer',
                'company_name' => 'WebCraft Agency',
                'company_logo_url' => null,
                'location' => 'Denver, CO',
                'salary_min' => 50000,
                'salary_max' => 75000,
                'job_type' => 'Freelance',
                'location_type' => 'Remote',
                'description' => 'We are looking for a freelance WordPress developer to build custom themes and plugins for our clients. Projects range from simple business sites to complex e-commerce platforms with WooCommerce integration.',
                'skills' => ['WordPress', 'PHP', 'JavaScript', 'WooCommerce', 'CSS'],
                'created_at' => now()->subDays(7),
            ],
            [
                'title' => 'Data Scientist',
                'company_name' => 'DataMinds Analytics',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=DM&background=06B6D4&color=fff',
                'location' => 'Boston, MA',
                'salary_min' => 140000,
                'salary_max' => 180000,
                'job_type' => 'Full-time',
                'location_type' => 'Hybrid',
                'description' => 'Join our data science team to build predictive models and extract insights from large datasets. You will work with machine learning algorithms, statistical analysis, and data visualization to drive business decisions.',
                'skills' => ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas'],
                'created_at' => now()->subDays(8),
            ],
            [
                'title' => 'Backend Node.js Developer',
                'company_name' => 'StreamLine Tech',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=SL&background=EF4444&color=fff',
                'location' => 'Portland, OR',
                'salary_min' => 100000,
                'salary_max' => 135000,
                'job_type' => 'Full-time',
                'location_type' => 'Remote',
                'description' => 'We need a backend developer proficient in Node.js to build and maintain our real-time messaging platform. Experience with WebSockets, message queues, and distributed systems is essential.',
                'skills' => ['Node.js', 'TypeScript', 'MongoDB', 'WebSockets', 'RabbitMQ'],
                'created_at' => now()->subDays(9),
            ],
            [
                'title' => 'QA Engineer (Part-time)',
                'company_name' => 'QualityFirst Software',
                'company_logo_url' => null,
                'location' => 'Miami, FL',
                'salary_min' => 35000,
                'salary_max' => 55000,
                'job_type' => 'Part-time',
                'location_type' => 'Hybrid',
                'description' => 'We are looking for a part-time QA engineer to develop and execute test plans, write automated tests, and ensure our software meets quality standards. Flexible hours with the option to increase to full-time.',
                'skills' => ['Selenium', 'Cypress', 'Test Automation', 'JIRA', 'API Testing'],
                'created_at' => now()->subDays(10),
            ],
            [
                'title' => 'Cloud Solutions Architect',
                'company_name' => 'SkyBridge Systems',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=SB&background=1D4ED8&color=fff',
                'location' => 'Washington, DC',
                'salary_min' => 150000,
                'salary_max' => 200000,
                'job_type' => 'Full-time',
                'location_type' => 'On-site',
                'description' => 'Lead the design and implementation of cloud-native architectures for enterprise clients. You will evaluate cloud services, design scalable solutions, and guide development teams through complex migrations.',
                'skills' => ['AWS', 'Azure', 'Cloud Architecture', 'Microservices', 'Security'],
                'created_at' => now()->subDays(11),
            ],
            [
                'title' => 'Junior Python Developer',
                'company_name' => 'CodeStart Labs',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=CS&background=059669&color=fff',
                'location' => 'Atlanta, GA',
                'salary_min' => 60000,
                'salary_max' => 80000,
                'job_type' => 'Full-time',
                'location_type' => 'Hybrid',
                'description' => 'Perfect role for early-career developers passionate about Python. You will work on web applications using Django, write clean code, participate in code reviews, and learn from experienced mentors.',
                'skills' => ['Python', 'Django', 'PostgreSQL', 'Git', 'REST APIs'],
                'created_at' => now()->subDays(12),
            ],
            [
                'title' => 'Cybersecurity Analyst (Contract)',
                'company_name' => 'SecureNet Defense',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=SN&background=DC2626&color=fff',
                'location' => 'Dallas, TX',
                'salary_min' => 90000,
                'salary_max' => 130000,
                'job_type' => 'Contract',
                'location_type' => 'On-site',
                'description' => 'Join our security operations team on a 12-month contract to monitor threats, conduct vulnerability assessments, and implement security controls. CISSP or CEH certification preferred.',
                'skills' => ['Network Security', 'Penetration Testing', 'SIEM', 'Firewalls', 'Incident Response'],
                'created_at' => now()->subDays(13),
            ],
            [
                'title' => 'Product Manager',
                'company_name' => 'InnoVenture Group',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=IV&background=7C3AED&color=fff',
                'location' => 'San Jose, CA',
                'salary_min' => 130000,
                'salary_max' => 165000,
                'job_type' => 'Full-time',
                'location_type' => 'Remote',
                'description' => 'We are seeking a Product Manager to define product strategy, prioritize features, and work cross-functionally with engineering, design, and marketing teams to deliver exceptional user experiences.',
                'skills' => ['Product Strategy', 'Agile', 'User Stories', 'Analytics', 'Roadmapping'],
                'created_at' => now()->subDays(14),
            ],
            [
                'title' => 'Freelance Graphic Designer',
                'company_name' => 'ArtVault Creative',
                'company_logo_url' => null,
                'location' => 'Nashville, TN',
                'salary_min' => 40000,
                'salary_max' => 65000,
                'job_type' => 'Freelance',
                'location_type' => 'Remote',
                'description' => 'Looking for a creative freelance graphic designer to produce brand assets, social media graphics, and marketing materials. Must have a strong portfolio demonstrating versatility across different styles.',
                'skills' => ['Adobe Photoshop', 'Illustrator', 'Brand Design', 'Typography', 'Social Media'],
                'created_at' => now()->subDays(15),
            ],
            [
                'title' => 'Full Stack Engineer',
                'company_name' => 'NexGen Digital',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=NG&background=0891B2&color=fff',
                'location' => 'Phoenix, AZ',
                'salary_min' => 105000,
                'salary_max' => 140000,
                'job_type' => 'Full-time',
                'location_type' => 'Hybrid',
                'description' => 'Build end-to-end features for our e-commerce platform. You will work across the stack from React frontends to Laravel backends, implementing payment integrations, inventory management, and real-time notifications.',
                'skills' => ['Laravel', 'React', 'MySQL', 'Redis', 'Stripe API'],
                'created_at' => now()->subDays(16),
            ],
            [
                'title' => 'Marketing Intern',
                'company_name' => 'GrowthPulse Marketing',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=GP&background=D97706&color=fff',
                'location' => 'Minneapolis, MN',
                'salary_min' => 18000,
                'salary_max' => 25000,
                'job_type' => 'Internship',
                'location_type' => 'On-site',
                'description' => 'Gain real-world marketing experience working on digital campaigns, social media management, email marketing, and analytics. Great opportunity for marketing students looking to build their portfolio.',
                'skills' => ['Digital Marketing', 'Google Analytics', 'Social Media', 'Email Marketing', 'Canva'],
                'created_at' => now()->subDays(17),
            ],
            [
                'title' => 'Database Administrator',
                'company_name' => 'DataVault Systems',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=DV&background=4338CA&color=fff',
                'location' => 'Philadelphia, PA',
                'salary_min' => 95000,
                'salary_max' => 125000,
                'job_type' => 'Full-time',
                'location_type' => 'On-site',
                'description' => 'Manage and optimize our MySQL and PostgreSQL database clusters. Responsibilities include performance tuning, backup strategies, replication setup, and ensuring data integrity across multiple environments.',
                'skills' => ['MySQL', 'PostgreSQL', 'Database Optimization', 'Backup & Recovery', 'Linux'],
                'created_at' => now()->subDays(18),
            ],
            [
                'title' => 'iOS Developer (Part-time)',
                'company_name' => 'SwiftApps Co.',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=SA&background=F43F5E&color=fff',
                'location' => 'San Diego, CA',
                'salary_min' => 55000,
                'salary_max' => 75000,
                'job_type' => 'Part-time',
                'location_type' => 'Remote',
                'description' => 'We need a part-time iOS developer to maintain and add features to our existing Swift-based application. Experience with SwiftUI, Core Data, and App Store submission process is required.',
                'skills' => ['Swift', 'SwiftUI', 'Core Data', 'Xcode', 'iOS SDK'],
                'created_at' => now()->subDays(19),
            ],
            [
                'title' => 'Technical Project Manager',
                'company_name' => 'AgileWorks Consulting',
                'company_logo_url' => null,
                'location' => 'Charlotte, NC',
                'salary_min' => 110000,
                'salary_max' => 145000,
                'job_type' => 'Contract',
                'location_type' => 'Hybrid',
                'description' => 'Lead cross-functional engineering teams through complex software delivery projects. You will manage timelines, remove blockers, facilitate ceremonies, and ensure alignment between stakeholders and development teams.',
                'skills' => ['Agile', 'Scrum', 'JIRA', 'Stakeholder Management', 'Risk Management'],
                'created_at' => now()->subDays(20),
            ],
            [
                'title' => 'Machine Learning Engineer',
                'company_name' => 'AI Frontier Labs',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=AF&background=7C3AED&color=fff',
                'location' => 'Remote, US',
                'salary_min' => 155000,
                'salary_max' => 210000,
                'job_type' => 'Full-time',
                'location_type' => 'Remote',
                'description' => 'Push the boundaries of AI by developing and deploying machine learning models at scale. Work on NLP, computer vision, and recommendation systems using cutting-edge frameworks and cloud infrastructure.',
                'skills' => ['Python', 'PyTorch', 'TensorFlow', 'MLOps', 'AWS SageMaker'],
                'created_at' => now()->subDays(21),
            ],
            [
                'title' => 'Freelance Video Editor',
                'company_name' => 'MotionCraft Media',
                'company_logo_url' => null,
                'location' => 'Remote, US',
                'salary_min' => 45000,
                'salary_max' => 70000,
                'job_type' => 'Freelance',
                'location_type' => 'Remote',
                'description' => 'Edit promotional videos, tutorials, and social media content for our tech clients. Must be proficient in Adobe Premiere Pro and After Effects with a strong sense of pacing and storytelling.',
                'skills' => ['Adobe Premiere Pro', 'After Effects', 'Video Editing', 'Motion Graphics', 'Color Grading'],
                'created_at' => now()->subDays(22),
            ],
            [
                'title' => 'Systems Administrator',
                'company_name' => 'NetCore Solutions',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=NC&background=0D9488&color=fff',
                'location' => 'Houston, TX',
                'salary_min' => 85000,
                'salary_max' => 110000,
                'job_type' => 'Full-time',
                'location_type' => 'On-site',
                'description' => 'Maintain and support our on-premise and hybrid infrastructure. Responsibilities include server management, network configuration, user access control, and disaster recovery planning.',
                'skills' => ['Linux', 'Windows Server', 'Networking', 'Active Directory', 'VMware'],
                'created_at' => now()->subDays(23),
            ],
            [
                'title' => 'Vue.js Frontend Developer',
                'company_name' => 'GreenLeaf Technologies',
                'company_logo_url' => 'https://ui-avatars.com/api/?name=GL&background=16A34A&color=fff',
                'location' => 'Remote, US',
                'salary_min' => 95000,
                'salary_max' => 130000,
                'job_type' => 'Full-time',
                'location_type' => 'Remote',
                'description' => 'Build interactive dashboards and data visualization tools using Vue.js and D3.js. You will collaborate with our product team to create intuitive interfaces for complex environmental data.',
                'skills' => ['Vue.js', 'JavaScript', 'D3.js', 'Tailwind CSS', 'REST APIs'],
                'created_at' => now()->subDays(24),
            ],
            [
                'title' => 'HR Coordinator Intern',
                'company_name' => 'PeopleFirst Corp',
                'company_logo_url' => null,
                'location' => 'Columbus, OH',
                'salary_min' => 15000,
                'salary_max' => 22000,
                'job_type' => 'Internship',
                'location_type' => 'Hybrid',
                'description' => 'Support the HR team with recruitment coordination, onboarding processes, and employee engagement initiatives. Ideal for HR students seeking practical experience in a fast-paced tech company.',
                'skills' => ['Recruitment', 'Communication', 'Microsoft Office', 'Organization', 'HRIS'],
                'created_at' => now()->subDays(25),
            ],
        ];

        foreach ($jobs as $job) {
            JobListing::create($job);
        }
    }
}
